name: Mirror url

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mirror
        run: |
          curl "https://go.dev/dl/?mode=json&include=all" -o github-versions.json

          git add github-versions.json
          git commit -m "chore: update github-versions.json from $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push