name: Mirror url

on:
  push:

  schedule:
    - cron: "0 0 * * *"
    
jobs:
  mirror:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mirror
        run: |
          curl "https://go.dev/dl/?mode=json&include=all" -o github-versions.json

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: daily update of github-versions.json"
